category_weights:
  API: 1.3
  CONTENT: 1.5
  DEPENDENCIES: 1.2
  MODELS: 2.0
  STRUCTURE: 1.0
ignored_validations:
- validate_dependency_version
- validate_dependency_line_length
- validate_dependency_distintas
- validate_dependency_stroke_width
- validate_dependency_max_length
- validate_dependency_max_digits
- validate_dependency_decimal_places
- validate_dependency_default
- validate_dependency_gt
- validate_dependency_ge
- validate_dependency_localhost
- validate_dependency_se
- validate_dependency_rev
- validate_dependency_node
- validate_dependency_nginx
- validate_env___example
- validate_pnpm_lock_yaml
- validate_vite_config__jt_s
- validate_wsgi_py
- validate_asgi_py
- validate_github_workflows____yaml
mandatory_validations:
- validate_directory_structure
- validate_django_models
- validate_django_settings_advanced
output:
  detailed_report: true
  encoding: utf-8
  safe_mode: true
  save_json: true
profiles:
  architecture_review:
    max_penalty_factor: 0.9
    min_score_threshold: 95
    required_categories:
    - STRUCTURE
    - CONTENT
    - MODELS
    - DEPENDENCIES
    - API
  ci_cd:
    max_penalty_factor: 0.5
    min_score_threshold: 75
    required_categories:
    - STRUCTURE
    - CONTENT
    - MODELS
  development:
    max_penalty_factor: 0.3
    min_score_threshold: 65
    required_categories:
    - STRUCTURE
    - MODELS
  moderate:
    max_penalty_factor: 0.5
    min_score_threshold: 75
    required_categories:
    - STRUCTURE
    - CONTENT
    - MODELS
  permissive:
    max_penalty_factor: 0.3
    min_score_threshold: 60
    required_categories:
    - STRUCTURE
  production:
    max_penalty_factor: 0.7
    min_score_threshold: 85
    required_categories:
    - STRUCTURE
    - CONTENT
    - MODELS
    - DEPENDENCIES
    - API
  strict:
    max_penalty_factor: 0.8
    min_score_threshold: 90
    required_categories:
    - STRUCTURE
    - CONTENT
    - MODELS
    - DEPENDENCIES
    - API
project_types:
  django_react:
    focus_categories:
    - MODELS
    - API
    - CONTENT
    ignore_missing_files:
    - docker-compose.yaml
  django_react_optimized:
    focus_categories:
    - MODELS
    - API
    ignore_missing_files:
    - docker-compose.yaml
    - .env.example
    - pnpm-lock.yaml
    - wsgi.py
    - asgi.py
    tolerance_overrides:
      missing_docker: true
      missing_frontend_lock: true
  django_simple:
    focus_categories:
    - MODELS
    - CONTENT
    ignore_missing_files:
    - docker-compose.yaml
    - Dockerfile
severity_weights:
  CRITICAL: 15
  HIGH: 8
  LOW: 1
  MEDIUM: 2
tolerance:
  missing_ci_cd: true
  missing_docker: true
  missing_documentation: true
  missing_env_example: true
  missing_frontend_lock: true
validation_profile: architecture_review
